version: "3"
services: 
    circleci-db:
        image: postgres:12.1
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "5432:5432"
        volumes:
            - "dbdata:/var/lib/postgresql/data/"
    circleci-django:
        build: .
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        command: >
            bash -c "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - circleci-db

volumes:
    dbdata:
        driver: local